/* SideHustle AI — hustle idea bank: 24 side hustles with skill/interest tags,
   weekly time need, startup cost (0-3), earning potential (1-5),
   monthly pay range at 10h/week, and first steps. */"use strict";

const SKILLS = ["writing","design","coding","teaching","organizing","cooking","photography","handyman","driving","pets","fitness","music","crafts","marketing","bookkeeping","gardening"];

const INTERESTS = ["tech","food","outdoors","kids","home","creative","people","animals","health","money"];

/* cost: 0=free 1=<$100 2=<$500 3=$500+ ; earning: 1..5 ; pay:[low,high] monthly at 10h/wk */
const HUSTLES = [
  { id:"freelance-writing", name:"Freelance writing", desc:"Blog posts, newsletters, and website copy for small businesses.",
    skills: ["writing"], interests: ["creative","money"], hours: 5, cost: 0, earning: 3, pay: [400, 2000],
    steps: ["Pick 1 niche (e.g. trades, SaaS, local services)","Write 3 portfolio samples","Create profiles on 2 freelance platforms","Pitch 10 local businesses this week"] },
  { id:"print-on-demand", name:"Print-on-demand designs", desc:"Sell t-shirt/mug designs with zero inventory.",
    skills: ["design"], interests: ["creative","money"], hours: 5, cost: 0, earning: 2, pay: [100, 1200],
    steps: ["Pick a niche audience","Make 10 designs in a free tool","Upload to 2 POD marketplaces","Post 1 design/day on social"] },
  { id:"tutoring", name:"Online tutoring", desc:"Teach math, science, or languages 1-on-1 by video.",
    skills: ["teaching"], interests: ["kids","people"], hours: 4, cost: 0, earning: 4, pay: [600, 2500],
    steps: ["List subjects you can teach confidently","Set up a tutor profile","Offer 3 free trial sessions","Ask every student for a review"] },
  { id:"pet-sitting", name:"Pet sitting / dog walking", desc:"Care for pets in your neighborhood; apps handle the bookings.",
    skills: ["pets"], interests: ["animals","outdoors"], hours: 6, cost: 0, earning: 3, pay: [500, 1800],
    steps: ["Sign up on 2 pet-care platforms","Get a background check done","Offer weekend availability first","Collect photo reviews from every client"] },
  { id:"meal-prep", name:"Meal-prep service", desc:"Cook weekly meal-prep boxes for busy locals.",
    skills: ["cooking","organizing"], interests: ["food","health"], hours: 8, cost: 1, earning: 4, pay: [800, 3000],
    steps: ["Design 1 weekly menu (5 meals)","Price 10 test boxes for neighbors","Check local cottage-food rules","Take standing weekly orders"] },
  { id:"handyman", name:"Odd-job handyman", desc:"Furniture assembly, mounting, small fixes — paid by the job.",
    skills: ["handyman"], interests: ["home","people"], hours: 6, cost: 1, earning: 4, pay: [700, 2800],
    steps: ["List tools you already own","Post on 2 local job boards","Price 3 common jobs flat-rate","Ask every client for a referral"] },
  { id:"bookkeeping", name:"Freelance bookkeeping", desc:"Monthly books for freelancers and tiny businesses.",
    skills: ["bookkeeping","organizing"], interests: ["money","tech"], hours: 5, cost: 0, earning: 4, pay: [800, 3500],
    steps: ["Learn one accounting tool deeply","Offer cleanup for 2 businesses free","Package a monthly flat-rate plan","Join a local business group"] },
  { id:"social-media", name:"Social media manager", desc:"Run content calendars for local businesses.",
    skills: ["marketing","writing"], interests: ["creative","people"], hours: 6, cost: 0, earning: 3, pay: [600, 2400],
    steps: ["Pick 1 platform to specialize in","Audit 5 local business accounts free","Build a 30-day content template","Pitch retainers, not one-offs"] },
  { id:"photo-mini", name:"Mini photo sessions", desc:"30-minute portrait sessions in parks; deliver 15 edited photos.",
    skills: ["photography"], interests: ["creative","people"], hours: 5, cost: 1, earning: 3, pay: [400, 2000],
    steps: ["Build a 20-photo portfolio","Pick 3 scenic local spots","Offer holiday mini-sessions","Deliver in 48h — speed wins referrals"] },
  { id:"lawn-care", name:"Weekend lawn care", desc:"Mowing, edging, leaf cleanup on a recurring route.",
    skills: ["gardening"], interests: ["outdoors","home"], hours: 8, cost: 2, earning: 3, pay: [600, 2200],
    steps: ["Price per-visit + monthly plans","Flyer 200 nearby homes","Book a tight route (less driving)","Upsell edging and cleanup"] },
  { id:"rideshare", name:"Rideshare / delivery driving", desc:"Drive evenings and weekends on your schedule.",
    skills: ["driving"], interests: ["money","people"], hours: 8, cost: 0, earning: 2, pay: [500, 1600],
    steps: ["Sign up on 2 driver apps","Track mileage from day one","Learn the busy hours in your area","Keep water + chargers in the car"] },
  { id:"fitness-coach", name:"Online fitness coaching", desc:"Custom workout plans + check-ins for remote clients.",
    skills: ["fitness","teaching"], interests: ["health","people"], hours: 5, cost: 0, earning: 3, pay: [500, 2500],
    steps: ["Get a basic certification","Coach 3 people free for testimonials","Build 4 plan templates","Charge monthly, not per-session"] },
  { id:"etsy-crafts", name:"Handmade goods shop", desc:"Sell crafts on Etsy or at local markets.",
    skills: ["crafts"], interests: ["creative","home"], hours: 8, cost: 1, earning: 2, pay: [200, 1500],
    steps: ["Make 10 units of your best item","Photograph in daylight","Open shop with 12+ listings","Do one local market for feedback"] },
  { id:"web-freelance", name:"Freelance web builds", desc:"Simple sites for local businesses that still have none.",
    skills: ["coding","design"], interests: ["tech","money"], hours: 8, cost: 0, earning: 5, pay: [1000, 5000],
    steps: ["Build 2 demo sites for fake businesses","Offer a fixed-price starter package","Pitch 20 local businesses","Add monthly care plans"] },
  { id:"music-lessons", name:"Music lessons", desc:"Teach guitar, piano, or voice locally or online.",
    skills: ["music","teaching"], interests: ["creative","kids"], hours: 4, cost: 0, earning: 3, pay: [400, 1800],
    steps: ["Define beginner curriculum (8 lessons)","Offer a free trial lesson","Post in parent/community groups","Sell 4-lesson packs"] },
  { id:"organizer", name:"Home organizer", desc:"Declutter closets, garages, and home offices by the project.",
    skills: ["organizing"], interests: ["home","people"], hours: 6, cost: 0, earning: 3, pay: [500, 2000],
    steps: ["Organize 2 friends' spaces for photos","Create before/after portfolio","Price by the project","Partner with a local mover"] },
  { id:"resume-service", name:"Resume + LinkedIn service", desc:"Rewrite resumes and profiles for job seekers.",
    skills: ["writing"], interests: ["people","money"], hours: 4, cost: 0, earning: 3, pay: [400, 1800],
    steps: ["Rewrite 3 resumes free for samples","Learn one ATS-friendly template","Offer 48-hour turnaround","Upsell LinkedIn rewrites"] },
  { id:"notary", name:"Mobile notary", desc:"Travel to clients for signings; loan signings pay best.",
    skills: ["organizing"], interests: ["money","people"], hours: 5, cost: 1, earning: 3, pay: [500, 2200],
    steps: ["Get commissioned in your state","Buy stamp + journal","Register on signing platforms","Offer evenings/weekends"] },
  { id:"car-detail", name:"Mobile car detailing", desc:"Interior/exterior detailing at the customer's driveway.",
    skills: ["handyman"], interests: ["outdoors","money"], hours: 8, cost: 2, earning: 4, pay: [800, 3000],
    steps: ["Build a starter kit (~$150)","Detail 3 cars for portfolio photos","Sell package tiers","Offer monthly maintenance plans"] },
  { id:"garden-install", name:"Garden bed installs", desc:"Build raised beds and plant starter gardens.",
    skills: ["gardening","handyman"], interests: ["outdoors","home"], hours: 8, cost: 2, earning: 3, pay: [600, 2400],
    steps: ["Build one demo bed","Price 4x8 and 4x4 installs","Flyer in spring","Offer seasonal refresh visits"] },
  { id:"video-edit", name:"Video editing", desc:"Edit shorts/reels for creators and local brands.",
    skills: ["design"], interests: ["tech","creative"], hours: 6, cost: 0, earning: 4, pay: [700, 3000],
    steps: ["Learn one editor well","Cut 5 spec edits","Niche down (e.g. realtors, gyms)","Sell monthly edit packs"] },
  { id:"errand-service", name:"Senior errand service", desc:"Groceries, prescriptions, and rides for older neighbors.",
    skills: ["driving","organizing"], interests: ["people","health"], hours: 6, cost: 0, earning: 2, pay: [400, 1400],
    steps: ["Flyer at community centers","Offer a weekly route day","Take recurring weekly clients","Get listed with local senior groups"] },
  { id:"newsletter", name:"Paid newsletter", desc:"Weekly niche newsletter with paid subscriptions.",
    skills: ["writing","marketing"], interests: ["creative","money"], hours: 5, cost: 0, earning: 2, pay: [50, 1500],
    steps: ["Pick a niche you read about anyway","Publish free weekly for 8 weeks","Add paid tier at 500 readers","Cross-promote with 5 similar newsletters"] },
  { id:"airbnb-cohost", name:"Airbnb co-hosting", desc:"Manage listings for owners: cleanings, guests, pricing.",
    skills: ["organizing","marketing"], interests: ["home","money"], hours: 8, cost: 0, earning: 4, pay: [800, 3500],
    steps: ["Learn dynamic pricing basics","Offer setup for 1 owner cheap","Systematize cleanings","Charge 15-20% of revenue"] }
];

const COST_LABELS = ["Free to start","Under $100","Under $500","$500+"];

if (typeof module !=="undefined" && module.exports) {
  module.exports = { SKILLS, INTERESTS, HUSTLES, COST_LABELS };
}
